### ISSUE TITLE
No Support for Unsafe Enchantments

### ISSUE THREAD

**Issue by FarazAlive78** [N3kas/AdvancedSets#20]
I'm trying to create a new weapon using AdvancedSets called "Golden Knife". It has sharpness 32767 (which is the maximum vanilla enchantment level in Vanilla Minecraft, 32768+ needs mods).

Problem? Unsafe enchants aren't supported for weapons. I get this error:

> [WARNING] Unexpected exception while parsing console command "asets reload"

org.bukkit.command.CommandException: Unhandled exception executing command 'asets' in plugin AdvancedSets v1.4.2

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]

Caused by: java.lang.IllegalArgumentException: Enchantment level is either too low or too high (given 32767, bounds are 1 to 5)

at org.bukkit.inventory.ItemStack.addEnchantment(ItemStack.java:438) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at gc.aas.weapons.c.<init>(c.java:59) ~[?:?]

at gc.aas.weapons.d.<init>(d.java:23) ~[?:?]

at gc.aas.a.e(a.java:104) ~[?:?]

at gc.aas.commands.a.onCommand(a.java:104) ~[?:?]

at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

... 8 more

**Comment by GC-spigot** [comment]
Added
