### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by gravityplayz** [N3kas/AdvancedSets#29]
version: latest
minecraft version: tacoSpigot 1.8.8
config: basic
description: i was wearing a set of the armour and spawned a mob with a spawn egg also u need to add a message when u use /aweapon with only a name as it give a arrayindexoutofbounds error just so u know.
error:
`26.09 01:16:42 [Server] Startup [05:16:42 ERROR]: Could not pass event PlayerInteractEvent to AdvancedSets v1.4.3
26.09 01:16:42 [Server] INFO org.bukkit.event.EventException
26.09 01:16:42 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) [?:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
26.09 01:16:42 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
26.09 01:16:42 [Server] INFO Caused by: java.lang.NullPointerException
26.09 01:16:42 [Server] INFO at gc.aas.handlers.SetEventHandler.c(SetEventHandler.java:235) ~[?:?]
26.09 01:16:42 [Server] INFO at gc.aas.listeners.RightClickEvent.a(RightClickEvent.java:25) ~[?:?]
26.09 01:16:42 [Server] INFO at sun.reflect.GeneratedMethodAccessor123.invoke(Unknown Source) ~[?:?]
26.09 01:16:42 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
26.09 01:16:42 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
26.09 01:16:42 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[CannonSpigot.jar:git-TacoSpigot-fd3209f3]
26.09 01:16:42 [Server] INFO ... 18 more`

**Comment by gravityplayz** [comment]
I was wearing the advancedset

**Comment by gravityplayz** [comment]
it happens when I place any block I think it has something to do with the set having a weapon
